Made it check for lockfiles before statings

diff --git a/simulate_requests b/simulate_requests
--- a/simulate_requests
+++ b/simulate_requests
@@ -22,15 +22,15 @@
 #
 ################################################################################
 #
-
 ################################################################################
 # The script get the current number of jobs in the queue.
 # Uses mkdir as a locking mechamism.
 ################################################################################
 get_wr_cnt () {
+  lockfile=$lfc
   i=0
   while [ $i -lt 100 -a $i -ge 0 ]; do
-    if mkdir $lfc > /dev/null 2>&1; then
+    if mkdir $lockfile > /dev/null 2>&1; then
       if [ -s $wrc ]; then
         cat $wrc
       else
@@ -44,11 +44,11 @@ get_wr_cnt () {
   done
 
   if [ $i -ge 100 ]; then
-    echo "Error, could not get lock on file '$lfc'." 1>&2
+    echo "Error, could not get lock on file '$lockfile'." 1>&2
     exit 1
   fi
 
-  rmdir $lfc
+  rmdir $lockfile
 }
 
 ################################################################################
@@ -56,9 +56,10 @@ get_wr_cnt () {
 # Uses mkdir as a locking mechamism.
 ################################################################################
 sub_wr_cnt () {
+  lockfile=$lfc
   i=0
   while [ $i -lt 100 -a $i -ge 0 ]; do
-    if mkdir $lfc > /dev/null 2>&1; then
+    if mkdir $lockfile > /dev/null 2>&1; then
       if [ -s $wrc ]; then
         x=$(cat $wrc)
       else
@@ -74,11 +75,11 @@ sub_wr_cnt () {
   done
 
   if [ $i -ge 100 ]; then
-    echo "Error, could not get lock on file '$lfc'." 1>&2
+    echo "Error, could not get lock on file '$lockfile'." 1>&2
     exit 1
   fi
 
-  rmdir $lfc
+  rmdir $lockfile
 }
 
 ################################################################################
@@ -86,9 +87,10 @@ sub_wr_cnt () {
 # Uses mkdir as a locking mechamism.
 ################################################################################
 add_wr_cnt () {
+  lockfile=$lfc
   i=0
   while [ $i -lt 100 -a $i -ge 0 ]; do
-    if mkdir $lfc > /dev/null 2>&1; then
+    if mkdir $lockfile > /dev/null 2>&1; then
       if [ -s $wrc ]; then
         x=$(cat $wrc)
       else
@@ -104,11 +106,11 @@ add_wr_cnt () {
   done
 
   if [ $i -ge 100 ]; then
-    echo "Error, could not get lock on file '$lfc'." 1>&2
+    echo "Error, could not get lock on file '$lockfile'." 1>&2
     exit 1
   fi
 
-  rmdir $lfc
+  rmdir $lockfile
 }
 
 ################################################################################
@@ -116,9 +118,10 @@ add_wr_cnt () {
 # Uses mkdir as a locking mechamism.
 ################################################################################
 update_results () {
+  lockfile=$lfr
   i=0
   while [ $i -lt 100 -a $i -ge 0 ]; do
-    if mkdir $lfr > /dev/null 2>&1; then
+    if mkdir $lockfile > /dev/null 2>&1; then
       echo "$*" >> $results
       i=-1
     else
@@ -128,11 +131,11 @@ update_results () {
   done
 
   if [ $i -ge 100 ]; then
-    echo "Error, could not get lock on file '$lfr'." 1>&2
+    echo "Error, could not get lock on file '$lockfile'." 1>&2
     exit 1
   fi
 
-  rmdir $lfr
+  rmdir $lockfile
 }
 
 ################################################################################
@@ -254,8 +257,11 @@ lfc=.lockfile-cnt
 lfr=.lockfile-results
 trap 'rm -f $wrc $tmpout; rmdir $lfc $lfr > /dev/null 2>&1' 0
 #
-# Ensure there isn't a left over lockfile from a previously aborted run.
+# Ensure there aren't any left over lockfiles from a previously aborted run.
 rmdir $lfc $lfr > /dev/null 2>&1
+# Since the old version of the script used files instead of directories, ensure
+# they don't exist either.
+rm -f $wrc $tmpout $lfc $lfr > /dev/null 2>&1
 # 
 #
 if which curl > /dev/null  2>&1; then
